# fly.toml app configuration file generated for full-stack-open-pokedex-weathered-pond-1509 on 2024-09-22T16:04:32+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-weathered-pond-1509'
primary_region = 'cdg'

[build]

[env]
  PORT = '3000'

[processes]
  app = 'node app.js'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  strategy = "bluegreen"

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/https://full-stack-open-pokedex-weathered-pond-1509.fly.dev/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
